### PR TITLE
Prefix form type options & code cleanup

### PR DESCRIPTION
**Pull request by jmsche**
Hi,

Sending a big PR :) 

Here's what's been done:

* Escape form options/variables with "froala_" namespace (cherry-picked from @mpoiriert commit)
* Support for ajax loading (cherry-picked from @mpoiriert commit)
* Add options related to FontAwesome third party plugin
* Add parameter types & return types everywhere possible
* Fix Twig extension
* Change directory structure
* Exclude some files & directories for releases
* Fix plugins' CSS not loaded correctly
* Don't load packaged Froala JS/CSS files as they contain all plugins
* Setup php-cs-fixer for Github Actions
* Setup phpstan for Github Actions
* README update

After merging this PR, **it will require a major version bump** (to 4.0.0) as it introduces huge BC breaks, eg. form type option prefixes and added parameter/return types.

Even if it's not really easy, could you please review the PR before merging it?

Thank you!

### CODE REVIEW

**Comment by sguionni** [comment]
I'm not using Symfony nor this bundlle since long time, so i'm not able to test/review the code

**Comment by sguionni** [comment]
@stefanneculai can you please add @jmsche to the Froala team and grant him rights to this repo ?

**Comment by jmsche** [comment]
Added options related to FontAwesome third party plugin.

**Comment by jmsche** [comment]
Hi @sguionni, while waiting for an answer from @stefanneculai could you please merge this PR & tag a 4.0.0 release?

This would allow to fix several issues for people, including the integration to Sonata & FontAwesome options.

**Comment by jmsche** [comment]
A big thank you :)

**Comment by sguionni** [comment]
Thank to you!
I can close #17 ?

**Comment by jmsche** [comment]
Sure :)

**Pull request merged**
