### PR TITLE
Massive upgrade :)

### PR DESCRIPTION
**Pull request by jmsche**
Hi,

Following the v3.0.0 upgrade, I did some changes that I wanted to do for a long time.

I couldn't split it into several PRs, but I could try if needed.

Here are the main changes:

* Symfony 4.3+ support only. I could try to make it compatible with 3.4+ (so 4.0+) if needed
* PHP 7.1+; stop supporting unsupported PHP versions
* Added a command to download the editor instead of putting files in the repository; then the bundle won't need an upgrade for a simple editor upgrade (excluding new options): `bin/console froala:install`
* Fixed most deprecations for Symfony 4.1+ (routing, container injection in controller, doctrine inflector...)
* The form widget layout is no longer loaded using DI; it will be added to configuration using the flex recipe (see https://github.com/symfony/recipes-contrib/pull/686)

The README.md file still needs an upgrade, but before doing it I'd like to get your feedback about this PR and know, if it's accepted, how tags/branches will be handled so I could redirect people to the right docs.

Thanks!

### CODE REVIEW

**Comment by sguionni** [comment]
Thanks for your work!
@stefanneculai what's your opinion about tags and branches?
For the moment i published with v3.0.0.

**Comment by jmsche** [comment]
@sguionni Could you please untag the 3.0.0 for the moment? It currently points to the master branch where changes are not available for the moment ;)

**Comment by sguionni** [comment]
Yep sorry i was too fast.
Tag and release are removed.

**Comment by jmsche** [comment]
@sguionni Can you also remove the tag from packagist please? See https://packagist.org/packages/kms/froala-editor-bundle

**Comment by sguionni** [comment]
Done, i thought it was automatic.

**Comment by jmsche** [comment]
Hello there, any news about branches/tags?

I thought a little about this, and here's what I think could work:

* Create a branch from `master` to eg. `v2` to keep Froala Editor v2.x available for updates if necessary
* Merge `v3` into `master` so `master` becomes again the way to go, and tag it to `3.0.0`. As there is a Download Command, there is no need to follow Froala Editor's tags anymore. So eg. for new features added in the bundle it would not require a new Froala Editor release to create a tag in the bundle, and the bundle could follow SemVer :)

An other possibility, but less fun:

* Create a branch from `master` to eg. `v2` to keep Froala Editor v2.x available for updates if necessary
* Merge `v3` into `master` so `master` becomes again the way to go, and tag it to `4.0.0`
* Rollback `v3` branch to this commit: https://github.com/froala/KMSFroalaEditorBundle/commit/1b64cfbbb4ef1657247efccd27d0959a3c77a307 and tag it to `3.0.0`

WDYT?

**Comment by sguionni** [comment]
@stefanneculai what do you think ?

**Comment by jmsche** [comment]
Hi @sguionni, can I ask you to make the decision here?

Seems @stefanneculai has no Github activities since two months :/

**Comment by sguionni** [comment]
@jmsche it's strange, @stefanneculai is in Froala official team.
Maybe he left.
You can take the decision you want, because i was the developper at the begining of this project but i'm not using Symfony nor PHP since years. So you can decide and i will merge.

**Comment by jmsche** [comment]
Here's what I'd like :smile: 

* create a branch from master to v2
* merge v3 in master, tag it as `3.0.0`
* delete v3 branch (and pr/45 branch?)

After everything is done I'll be able to create docs for last release & fix the recipe :smile: 

Thank you!

**Comment by sguionni** [comment]
It's done :)

**Comment by jmsche** [comment]
There's a huge problem: the v3 branch was not merged in master :'(

**Comment by jmsche** [comment]
I could try to re-PR my v3 branch against master if needed

**Comment by sguionni** [comment]
Sorry i did a mistake.
Yes it should be safe to do another clean PR against master.

**Pull request merged**
