### PR TITLE
[WIP] escape form options/variables with froala namespace

### PR DESCRIPTION
**Pull request by mpoiriert**
This will show how this fix will be done.

There is a discrepancy with coding standard since my computer is set up for Symfony CS and the repository is now following it (big one is tab -> space).

I have test it (without any configured) and it's working so far.

### CODE REVIEW

**Comment by jmsche** [comment]
@sguionni @mpoiriert AFAICT this would require a major release? I think this is included in the last patch release

**Comment by jmsche** [comment]
@sguionni As expected this PR is a huge BC break... Updating from 3.1.0 to 3.1.1 is throwing errors as the option names have changed.

Could you please revert this commit, create a new patch release (3.1.2) and drop the current one (3.1.1) from Github & Packagist?

If you do so, I'll try to come up with code style & static analysis this week so a new major version could be released, along with @mpoiriert's changes to move the options "namespace".

**Comment by sguionni** [comment]
Revert the 2 commits from this PR?

**Comment by jmsche** [comment]
Yes

**Comment by sguionni** [comment]
It's done

**Comment by jmsche** [comment]
Thank you :) I'll start to work on it right away

**Comment by jmsche** [comment]
Could also please remove `v3.2.0` branch, and create a `v3` branch from master? So when merging the upcoming PR(s) in master it won't mess with it

**Comment by sguionni** [comment]
Ops, just did it

**Comment by jmsche** [comment]
Not a problem, see comment in #120

**Pull request merged**
