### PR TITLE
Updated to v3

### PR DESCRIPTION
**Pull request by Geet06**
The froala-editor files were not getting downloaded on running `composer require kms/froala-editor-bundle` so added the editor files

### CODE REVIEW

**Comment by sguionni** [comment]
@jmsche maybe something is missing in the documentation, because we don't need to provide froala sources anymore in the bundle with your upgrade.

**Comment by jmsche** [comment]
It's documented! :)

See:

* Step 7: install asset files - https://github.com/froala/KMSFroalaEditorBundle#step-7-install-asset-files
* Or, Webpack encore configuration - https://github.com/froala/KMSFroalaEditorBundle#webpack-encore-configuration

**Comment by jmsche** [comment]
Didn't see this was a PR, so I'd be :-1: for it, sorry :)

**Comment by sguionni** [comment]
Yes you're right, i'll not merge this, sorry @Geet06  but please follow install instructions.

**Pull request closed without merging**
