### PR TITLE
Updated for Symfony 4 compatibility

### LINKED ISSUE #39: Symfony 4 support
Can you add in symfony 4 support?

### PR DESCRIPTION
**Pull request by jmsche**
Fixes #39.

### CODE REVIEW

**Comment by samarhxc** [comment]
Thanks for this!
Did you test the backward compatibility with Sf 2 & 3?

**Comment by jmsche** [comment]
Hi, sorry I had no chance to do this - yet.

Can you test this? If not I'll try to do this tomorrow or this weekend.

**Comment by samarhxc** [comment]
Sorry i have no time to do this this week :/
Regarding changes i think it's ok but i prefer test before merging :)

**Comment by samarhxc** [comment]
Thanks for your contribution!

**Pull request merged**
